# Generated by Django 4.1.1 on 2022-09-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_provider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordkeeper',
            old_name='password',
            new_name='private_key',
        ),
        migrations.AddField(
            model_name='passwordkeeper',
            name='crypto_type',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passwordkeeper',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
